[2024-04-10T08:55:45.842+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-10T08:55:45.937+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_airbyte_job_example.airbyte_check_sync manual__2024-04-10T08:55:34.488860+00:00 [queued]>
[2024-04-10T08:55:45.964+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_airbyte_job_example.airbyte_check_sync manual__2024-04-10T08:55:34.488860+00:00 [queued]>
[2024-04-10T08:55:45.965+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-10T08:55:46.009+0000] {taskinstance.py:2327} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-04-10 08:55:34.488860+00:00
[2024-04-10T08:55:46.036+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=437) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-10T08:55:46.040+0000] {standard_task_runner.py:63} INFO - Started process 446 to run task
[2024-04-10T08:55:46.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_airbyte_job_example', 'airbyte_check_sync', 'manual__2024-04-10T08:55:34.488860+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_aribyte_ex.py', '--cfg-path', '/tmp/tmpj2ag6036']
[2024-04-10T08:55:46.045+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask airbyte_check_sync
[2024-04-10T08:55:46.206+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_airbyte_job_example.airbyte_check_sync manual__2024-04-10T08:55:34.488860+00:00 [running]> on host ff62e46d2b31
[2024-04-10T08:55:46.497+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_airbyte_job_example' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T08:55:34.488860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-10T08:55:34.488860+00:00'
[2024-04-10T08:55:46.510+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-10T08:55:46.511+0000] {baseoperator.py:399} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-04-10T08:55:46.538+0000] {base.py:84} INFO - Using connection ID '***_call_airbyte' for task execution.
[2024-04-10T08:55:46.644+0000] {airbyte.py:104} INFO - Waiting for job 138 to complete.
[2024-04-10T08:56:46.662+0000] {base.py:84} INFO - Using connection ID '***_call_airbyte' for task execution.
[2024-04-10T08:56:46.738+0000] {airbyte.py:99} INFO - Job 138 completed successfully.
[2024-04-10T08:56:46.738+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-10T08:56:46.739+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-10T08:56:46.753+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=trigger_airbyte_job_example, task_id=airbyte_check_sync, execution_date=20240410T085534, start_date=20240410T085545, end_date=20240410T085646
[2024-04-10T08:56:46.788+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-10T08:56:46.817+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-10T08:56:46.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
